services:
  app:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - .:/home/node/app
    depends_on:
      - mongo

  mongo:
    build: ./.docker/mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - 27017:27017
